# Generated by Django 4.0.5 on 2022-06-22 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_remove_acquiredskill_user_remove_certificate_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='user',
        ),
    ]
