# Generated by Django 4.0.5 on 2022-06-23 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_remove_project_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'project', 'verbose_name_plural': 'projects'},
        ),
        migrations.AddField(
            model_name='project',
            name='hosted_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterModelTable(
            name='project',
            table='projects',
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='project_pics')),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.project')),
            ],
            options={
                'verbose_name': 'project image',
                'verbose_name_plural': 'project images',
                'db_table': 'project_images',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='main_image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.projectimage'),
        ),
    ]
