# Generated by Django 4.0.5 on 2022-06-23 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_project_options_project_hosted_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='photo',
            field=models.ImageField(blank=True, upload_to='uploads/images/certificate_pics/'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(upload_to='uploads/images/project_pics/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.ImageField(blank=True, upload_to='uploads/images/service_icons/'),
        ),
        migrations.AlterField(
            model_name='social',
            name='icon',
            field=models.ImageField(blank=True, upload_to='uploads/images/social_icons/'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='photo',
            field=models.ImageField(blank=True, upload_to='uploads/images/testimonial_pics/'),
        ),
    ]
