# Generated by Django 4.0.5 on 2022-06-29 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_career'),
        ('accounts', '0003_alter_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='careers',
            field=models.ManyToManyField(to='backend.career'),
        ),
    ]
